import type { Context } from "../ui/context";
import { loadCatalog } from "../services/catalog";
import { loadEnrollments, removeEnrollment, saveEnrollment, saveEnrollments, semesterLabel } from "../services/enrollment";
import { e } from "../utils/html";
import { href } from "../utils/routes";
import { heading } from "../ui/shell";
import { badge, confirmAction, empty, toast } from "../ui/primitives";
import { icon } from "../ui/icons";

export function renderEnrollment(ctx:Context){
  if(ctx.user.role!=="student"){ctx.root.innerHTML=empty("หน้านี้สำหรับนิสิต","ผู้ดูแลไม่จำเป็นต้องลงทะเบียนรายวิชา");return;}
  const catalog=loadCatalog(ctx.data.assignments),years=[...new Set(catalog.subjects.map(row=>row.academicYear))].sort((a,b)=>b-a);
  let enrollments=loadEnrollments(ctx.user.uid),year="ALL",semester="ALL",visibleSubjects:typeof catalog.subjects=[];
  ctx.root.innerHTML=heading("รายวิชาของฉัน","เลือกรายวิชาและ Sec ที่เรียน ระบบจะใช้ข้อมูลนี้กรองงาน ปฏิทิน และประกาศทางการ","MY COURSES",'<a class="button" href="'+href("dashboard")+'">'+icon("left")+' กลับภาพรวม</a>')+
  `<div class="enrollment-summary" id="enrollment-summary"></div>
  <section class="panel"><div class="panel-title"><div><h2>ค้นหารายวิชาที่เปิดสอน</h2><p class="note-hint">หนึ่งรายวิชาลงทะเบียนได้หนึ่ง Sec และแก้ไขภายหลังได้</p></div></div><div class="filter-panel enrollment-filters"><label>ปีการศึกษา<select id="enrollment-year"><option value="ALL">ทุกปีการศึกษา</option>${years.map(value=>`<option value="${value}">${value}</option>`).join("")}</select></label><label>ภาคเรียน<select id="enrollment-semester"><option value="ALL">ทุกภาคเรียน</option><option value="1">ภาคเรียนที่ 1</option><option value="2">ภาคเรียนที่ 2</option></select></label></div><div class="registration-check-link"><div><strong>จำ Sec ที่เรียนไม่ได้?</strong><span>ตรวจสอบข้อมูลการลงทะเบียนของคุณก่อนเลือกกลุ่มเรียน</span></div><a class="button primary small" href="https://reg.up.ac.th/" target="_blank" rel="noopener noreferrer">ตรวจสอบ Sec ที่ระบบทะเบียน ↗</a></div><div id="course-options"></div></section>`;
  const summary=ctx.root.querySelector<HTMLElement>("#enrollment-summary")!,options=ctx.root.querySelector<HTMLElement>("#course-options")!;
  const render=()=>{
    const active=enrollments.map(enrollment=>({enrollment,subject:catalog.subjects.find(row=>row.id===enrollment.subject_id)})).filter(row=>row.subject);
    summary.innerHTML=active.length?`<section class="panel enrollment-current"><div class="panel-title"><div><h2>ลงทะเบียนแล้ว ${active.length} วิชา</h2><p class="note-hint">ระบบจะแสดงเฉพาะข้อมูลของ Sec ที่เลือกในแต่ละวิชา</p></div>${badge("ตั้งค่าครบแล้ว","done")}</div><div class="enrollment-chips">${active.map(({enrollment,subject})=>`<div class="enrollment-chip"><div><strong>${e(subject!.name)}</strong><span>ปี ${subject!.academicYear} · ${e(semesterLabel(subject!.semester))} · Sec ${enrollment.section}</span></div><button class="icon-button" type="button" data-remove-enrollment="${e(subject!.id)}" aria-label="ถอน ${e(subject!.name)}">${icon("trash")}</button></div>`).join("")}</div></section>`:`<div class="onboarding-callout">${icon("book")}<div><h2>เริ่มต้นด้วยการลงทะเบียนรายวิชา</h2><p>เมื่อเลือกวิชาและ Sec แล้ว หน้าแดชบอร์ด งาน ปฏิทิน และประกาศทางการจะแสดงข้อมูลที่ตรงกับคุณ</p></div></div>`;
    visibleSubjects=catalog.subjects.filter(row=>(year==="ALL"||row.academicYear===Number(year))&&(semester==="ALL"||row.semester===semester)).sort((a,b)=>b.academicYear-a.academicYear||a.semester.localeCompare(b.semester)||a.name.localeCompare(b.name));
    options.innerHTML=visibleSubjects.length?`<div class="course-option-list">${visibleSubjects.map(subject=>{const current=enrollments.find(row=>row.subject_id===subject.id);return `<article class="course-option ${current?"registered":""}"><div class="course-option-main"><span class="subject-icon">${icon("book")}</span><div><h3>${e(subject.name)}</h3><p>ปีการศึกษา ${subject.academicYear} · ${e(semesterLabel(subject.semester))} · เปิด ${subject.sectionCount} Sec</p></div></div><label>กลุ่มเรียน<select data-enrollment-section="${e(subject.id)}"><option value="">เลือก Sec</option>${Array.from({length:subject.sectionCount},(_,index)=>`<option value="${index+1}" ${current?.section===index+1?"selected":""}>Sec ${index+1}</option>`).join("")}</select></label><button class="button ${current?"":"primary"}" type="button" data-save-enrollment="${e(subject.id)}">${current?"บันทึก Sec":"ลงทะเบียน"}</button></article>`;}).join("")}</div><div class="enrollment-bulk-footer"><div><strong>ตรวจสอบ Sec ก่อนบันทึก</strong><span>วิชาที่ยังไม่ลงทะเบียนต้องเลือก Sec ให้ครบ การบันทึกซ้ำจะอัปเดตข้อมูลเดิม</span></div><button class="button primary" type="button" data-save-all-enrollments>${enrollments.length?"บันทึกการเปลี่ยนแปลงทั้งหมด":"ลงทะเบียนทั้งหมด"} ${visibleSubjects.length} วิชา</button></div>`:empty("ไม่พบรายวิชา","ลองเปลี่ยนปีการศึกษาหรือภาคเรียน หรือให้ผู้ดูแลเพิ่มรายวิชาในข้อมูลพื้นฐาน");
  };
  ctx.root.addEventListener("change",event=>{const select=event.target as HTMLSelectElement;if(select.id==="enrollment-year"){year=select.value;render();}else if(select.id==="enrollment-semester"){semester=select.value;render();}});
  ctx.root.addEventListener("click",event=>{const button=(event.target as Element).closest<HTMLButtonElement>("button");if(!button)return;
    if(button.dataset.saveEnrollment){const subject=catalog.subjects.find(row=>row.id===button.dataset.saveEnrollment),select=options.querySelector<HTMLSelectElement>(`[data-enrollment-section="${button.dataset.saveEnrollment}"]`);if(!subject||!select)return;try{enrollments=saveEnrollment(ctx.user.uid,subject,Number(select.value));ctx.enrollments=enrollments;render();toast(`บันทึก ${subject.name} · Sec ${select.value} แล้ว`);}catch(error){toast(error instanceof Error?error.message:"บันทึกไม่สำเร็จ",true);}}
    if(button.hasAttribute("data-save-all-enrollments")){try{const selections=visibleSubjects.map(subject=>{const select=options.querySelector<HTMLSelectElement>(`[data-enrollment-section="${subject.id}"]`);return {subject,section:Number(select?.value)};});enrollments=saveEnrollments(ctx.user.uid,selections);ctx.enrollments=enrollments;render();toast(`บันทึกการลงทะเบียน ${selections.length} วิชาแล้ว`);}catch(error){toast(error instanceof Error?error.message:"บันทึกทั้งหมดไม่สำเร็จ",true);}}
    if(button.dataset.removeEnrollment){const subject=catalog.subjects.find(row=>row.id===button.dataset.removeEnrollment);if(!subject)return;void confirmAction("ถอนรายวิชา",`ต้องการถอน ${subject.name} ออกจากรายวิชาของฉันใช่ไหม ข้อมูลความคืบหน้าจะไม่ถูกลบ`,"ถอนรายวิชา").then(confirmed=>{if(!confirmed)return;enrollments=removeEnrollment(ctx.user.uid,subject.id);ctx.enrollments=enrollments;render();toast("ถอนรายวิชาแล้ว");});}
  });render();
}
